### PR TITLE
Deployments History commit to Asgrim:develop

### PR DESCRIPTION
**Pull request by ghost**
My first commit for the deployments history page. Includes controller,view and css file.

(take two)

### CODE REVIEW

**Comment by ghost** [comment]
I tried to send to "Asgrim:deployments-history" but it didn't update from Asgrim:develop, oh well!

**Comment by asgrim** [comment]
Simon - I have noticed your commits are coming from user "root". Please use git config to update this (it is advisable not to change the existing commits as you have already pushed, but future commits should be set correctly). 

``` bash
$ git config --global user.name "Simon Wade"
$ git config --global user.email "your_email@youremail.com"
```

I think the e-mail address used should be the same as your github account but I don't think this is a hard and fast rule.

**Comment by ghost** [comment]
ok did this

**Comment by asgrim** [comment]
Did what?! o_O

**Comment by ghost** [comment]
Updated my git config!!>>!??!111 :)

**Comment by asgrim** [comment]
Oh ok good job. Tally ho.

**Pull request merged**
