### PR TITLE
Two Commits

### PR DESCRIPTION
**Pull request by ghost**
Two commits - fixed header, added slug renaming to edit project form.

### CODE REVIEW

**Comment by asgrim** [comment]
Thanks Simon. I won't merge this just yet as I need to repackage the libraries etc.

**Comment by ghost** [comment]
Np, i noticed theres several "Merge branch" messages along with my commits... not entirely sure what those are yet! Let me know if you need anything done.

**Comment by asgrim** [comment]
I have merged the h2 sub heading into my repo (see ba4b4a8bd1cddbc5d8bbcf9bb820ae1c3ad72a57) but I'm not sure about the ability to change the slug any more. There is no official update procedure for updating MAL in existing GoDeploy installations, and because they are static zips rather than git clones, it is not easy just to "git pull" like we do to upgrade GoDeploy. That's the showstopper for this really - can you think of a way around this?

**Comment by ghost** [comment]
Well I guess the only other options are to not update the slug, or move the method to the godeploy repo (which I would say is not desirable)? :)

**Comment by asgrim** [comment]
OK - lets sack this off then :)

**Pull request closed without merging**
